# Generated by Django 5.1.6 on 2025-02-27 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, default='', help_text='Age of the patient', null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', help_text='Sex of the patient', max_length=1, null=True)),
                ('cp', models.PositiveIntegerField(blank=True, default='', help_text='Chest pain type', null=True)),
                ('trestbps', models.PositiveIntegerField(blank=True, default='', help_text='Resting blood pressure', null=True)),
                ('chol', models.PositiveIntegerField(blank=True, default='', help_text='Serum cholesterol', null=True)),
                ('fbs', models.PositiveIntegerField(blank=True, default='', help_text='Fasting blood sugar', null=True)),
                ('restecg', models.PositiveIntegerField(blank=True, default='', help_text='Resting electrocardiographic results', null=True)),
                ('thalach', models.PositiveIntegerField(blank=True, default='', help_text='Maximum heart rate achieved', null=True)),
                ('exang', models.PositiveIntegerField(blank=True, default='', help_text='Exercise induced angina', null=True)),
                ('oldpeak', models.FloatField(blank=True, default='', help_text='ST depression induced by exercise relative to rest', null=True)),
                ('slope', models.PositiveIntegerField(blank=True, default='', help_text='Slope of the peak exercise ST segment', null=True)),
                ('ca', models.PositiveIntegerField(blank=True, default='', help_text='Number of major vessels (0-3) colored by flourosopy', null=True)),
                ('thal', models.CharField(blank=True, choices=[('N', 'Normal'), ('Y', 'Yes'), ('R', 'Reversible defect')], default='', help_text='Thalassemia', max_length=1, null=True)),
                ('prediction', models.IntegerField(blank=True, help_text='The prediction made by the model', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
